### ISSUE TITLE
0.0.1 에러 정리, Todo 정리

### ISSUE THREAD

**Issue by srngch** [srngch/vanilla-js-calculator#2]
https://github.com/srngch/vanilla-js-calculator/pull/1 에서 해결되지 못 한 내용을 포함한 Todo

- [ ] `AC`/`C` 버튼: 계산 이후 작동 방식
  - `=` 버튼 누른 이후에 `C` 버튼을 누르면 초기화 되도록
- [ ] `.` 버튼 소수점 입력
- [ ] 부동소수점 계산 에러
- [ ] 퍼센트 버튼 작동 방식, 계산
  - ` 1` `% ` -> `0.01` 출력, ` +` `1` `= ` -> `2` 출력, (올바른 값: `1.01` 출력)
  - ` 1` `% ` -> `0.01` 출력, `2` -> `12`(올바른 값: `0.01`은 사라지고 `2` 출력)
- [ ] 0과 나누기 계산
  - `0` 나누기 계산을 해서 `Infinity` 출력, `%` `숫자` `=`반복 시 숫자가 초기화되지 않고 오류 반복
